name: Docker Image CI

on:
  release:
    types: [published]    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2    

      - name: Build and push the Docker image
        uses: docker/build-push-action@v1
      
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: urbanandco/keycloak-training
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}      
      
